language: node_js
sudo: false

os: linux

addons:
  chrome: stable

node_js:
  - "12.14.1"

install:
  - npm ci

script:
  - npm run lib:prod
  - CHROMIUM_BIN="/usr/bin/google-chrome" npm test
  - EXAMPLES_SCRIPTS_URL_PREFIX="https://kp-sys.github.io/angularjs-value-editor" npm run docs:build
  - npm run lib:dts

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    local_dir: "docs"
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
