language: node_js
sudo: false

os: linux

addons:
  chrome: stable

env:
  global:
    - NODE_VERSION=10

before_install:
  - nvm install $NODE_VERSION
  - npm install -g npm@6 && node -v && npm -v

install:
  - npm ci

script:
  - npm run lib:prod
  - CHROMIUM_BIN="/usr/bin/google-chrome" npm test
  - EXAMPLES_SCRIPTS_URL_PREFIX="https://kp-sys.github.io/angularjs-value-editor" npm run docs:build

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    local_dir: "docs"
    on:
      branch: master

  - provider: npm
    email: "tomas.dostal@kpsys.cz"
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      branch: master
